use std::context::Context


contract Wave {

   totalWaves: Map<address,u256>
   
  event Greet {
    greeting: String<100>
  }

   
    pub fn wave(self,ctx:Context) {
       self.totalWaves[ctx.msg_sender()] += 1
       pub fn __inmit__(ctx:Context, greeting: String<100>) {
        emit Greet(ctx)
       }
    }
    
    
    pub fn getTotalWaves(self, addr: address)-> u256{
        
        return self.totalWaves[addr]
    }

   
}